name 'petclinic'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures petclinic'
version '0.1.0'
chef_version '>= 16.0'

depends 'aws', '~> 9.0.2'
depends 'java', '~> 11.1.0'